# Generated by Django 5.2.5 on 2025-09-29 20:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}-[0-9kK]$', 'Formato: 12345678-9')])),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('tipo_cliente', models.CharField(choices=[('empresa', 'Empresa'), ('particular', 'Particular'), ('gobierno', 'Gobierno')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_servicio', models.CharField(choices=[('electrico', 'Instalaciones Eléctricas'), ('incendio', 'Sistemas de Detección de Incendios'), ('construccion', 'Construcción'), ('programacion', 'Programación')], max_length=20)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tipo_servicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('administrador', 'Administrador'), ('cliente', 'Cliente'), ('empleado', 'Empleado'), ('contratista', 'Contratista')], default='cliente', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('rut', models.CharField(blank=True, max_length=12)),
                ('direccion', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField()),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('cotizado', 'Cotizado'), ('aprobado', 'Aprobado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('pausado', 'Pausado')], default='cotizado', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('presupuesto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='siriusApp.cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL)),
                ('servicios', models.ManyToManyField(related_name='proyectos', to='siriusApp.servicio')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_presupuesto', models.CharField(blank=True, max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_emision', models.DateField()),
                ('validez_dias', models.IntegerField(default=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='siriusApp.cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='siriusApp.proyecto')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_incidencia', models.CharField(choices=[('tecnica', 'Técnica'), ('administrativa', 'Administrativa'), ('cliente', 'Del Cliente'), ('proveedor', 'Del Proveedor'), ('calidad', 'Control de Calidad')], max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_proceso', 'En Proceso'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], default='abierta', max_length=15)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('solucion', models.TextField(blank=True)),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Subir archivos relacionados (fotos, documentos, etc.)', null=True, upload_to='incidencias/%Y/%m/')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to=settings.AUTH_USER_MODEL)),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='siriusApp.proyecto')),
            ],
            options={
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
